// <auto-generated />
namespace FSS.Omnius.Modules.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gendatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gendatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201602260902018_gendatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
