// <auto-generated />
namespace FSS.Omnius.Modules.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class isLocalUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isLocalUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201602091209188_isLocalUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
