// <auto-generated />
namespace FSS.Omnius.Modules.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class actionRule_Action_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actionRule_Action_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201604130808394_actionRule_Action_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
