// <auto-generated />
namespace FSS.Omnius.Modules.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dev_Grid_Work_Merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dev_Grid_Work_Merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201708141059461_Dev_Grid_Work_Merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
