namespace FSS.Omnius.Modules.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cascadeTrigger : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Tapestry_ActionRule_Action", "ActionRuleId", "dbo.Tapestry_ActionRule");
            DropForeignKey("dbo.Persona_ActionRuleRights", "ActionRuleId", "dbo.Tapestry_ActionRule");
            DropForeignKey("dbo.Tapestry_ActionRule", "SourceBlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Persona_ActionRuleRights", "AppRoleId", "dbo.Persona_AppRoles");
            DropForeignKey("dbo.Persona_AppRoles", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Entitron_ColumnMetadata", "Application_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.Entitron_DbSchemeCommit", "Application_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.Hermes_Incoming_Email_Rule", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Mozaic_Js", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.MozaicBootstrap_Page", "ParentApp_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.MozaicEditor_Pages", "ParentApp_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.TapestryDesigner_MetaBlocks", "ParentAppId", "dbo.Master_Applications");
            DropForeignKey("dbo.Nexus_TCP_Socket_Listener", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Master_UsersApplications", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Tapestry_WorkFlow", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Persona_ADgroup_User", "ADgroupId", "dbo.Persona_ADgroups");
            DropForeignKey("dbo.Persona_ADgroup_User", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_UserClaim", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_UserLogin", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_ModuleAccessPermissions", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_Identity_UserRoles", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_User_Role", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Master_UsersApplications", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_User_Role", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Entitron_DbRelation", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Entitron_DbTable", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Entitron_DbView", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Entitron_DbRelation", "LeftColumnId", "dbo.Entitron_DbColumn");
            DropForeignKey("dbo.Entitron_DbRelation", "LeftTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbRelation", "RightColumnId", "dbo.Entitron_DbColumn");
            DropForeignKey("dbo.Entitron_DbRelation", "RightTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbColumn", "DbTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbIndex", "DbTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Hermes_Incoming_Email_Rule", "IncomingEmailId", "dbo.Hermes_Incoming_Email");
            DropForeignKey("dbo.MozaicBootstrap_Components", "MozaicBootstrapPageId", "dbo.MozaicBootstrap_Page");
            DropForeignKey("dbo.MozaicEditor_Components", "MozaicEditorPageId", "dbo.MozaicEditor_Pages");
            DropForeignKey("dbo.TapestryDesigner_ResourceItems", "ParentRuleId", "dbo.TapestryDesigner_ResourceRules");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "SourceId", "dbo.TapestryDesigner_ResourceItems");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "TargetId", "dbo.TapestryDesigner_ResourceItems");
            DropForeignKey("dbo.TapestryDesigner_ConditionSets", "ConditionGroupId", "dbo.TapestryDesigner_ConditionGroups");
            DropForeignKey("dbo.TapestryDesigner_Conditions", "TapestryDesignerConditionSet_Id", "dbo.TapestryDesigner_ConditionSets");
            DropForeignKey("dbo.TapestryDesigner_WorkflowItems", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "SourceId", "dbo.TapestryDesigner_WorkflowItems");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "TargetId", "dbo.TapestryDesigner_WorkflowItems");
            DropForeignKey("dbo.TapestryDesigner_Foreach", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_Swimlanes", "ParentWorkflowRule_Id", "dbo.TapestryDesigner_WorkflowRules");
            DropForeignKey("dbo.TapestryDesigner_Subflow", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "WorkflowRuleId", "dbo.TapestryDesigner_WorkflowRules");
            DropForeignKey("dbo.TapestryDesigner_WorkflowRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits");
            DropForeignKey("dbo.TapestryDesigner_BlocksCommits", "ParentBlock_Id", "dbo.TapestryDesigner_Blocks");
            DropForeignKey("dbo.TapestryDesigner_ResourceRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits");
            DropForeignKey("dbo.TapestryDesigner_Blocks", "ParentMetablock_Id", "dbo.TapestryDesigner_MetaBlocks");
            DropForeignKey("dbo.TapestryDesigner_MetablocksConnections", "TapestryDesignerMetablockId", "dbo.TapestryDesigner_MetaBlocks");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "ResourceRuleId", "dbo.TapestryDesigner_ResourceRules");
            DropForeignKey("dbo.Tapestry_Blocks", "WorkFlowId", "dbo.Tapestry_WorkFlow");
            DropForeignKey("dbo.Tapestry_AttributeRules", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Tapestry_PreBlockActions", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Tapestry_ResourceMappingPairs", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Mozaic_CssPages", "CssId", "dbo.Mozaic_Css");
            DropForeignKey("dbo.Mozaic_CssPages", "PageId", "dbo.Mozaic_Pages");
            DropForeignKey("dbo.Mozaic_Template", "CategoryId", "dbo.Mozaic_TemplateCategories");
            AddForeignKey("dbo.Tapestry_ActionRule_Action", "ActionRuleId", "dbo.Tapestry_ActionRule", "Id");
            AddForeignKey("dbo.Persona_ActionRuleRights", "ActionRuleId", "dbo.Tapestry_ActionRule", "Id");
            AddForeignKey("dbo.Tapestry_ActionRule", "SourceBlockId", "dbo.Tapestry_Blocks", "Id");
            AddForeignKey("dbo.Persona_ActionRuleRights", "AppRoleId", "dbo.Persona_AppRoles", "Id");
            AddForeignKey("dbo.Persona_AppRoles", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Entitron_ColumnMetadata", "Application_Id", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Entitron_DbSchemeCommit", "Application_Id", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Hermes_Incoming_Email_Rule", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Mozaic_Js", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.MozaicBootstrap_Page", "ParentApp_Id", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.MozaicEditor_Pages", "ParentApp_Id", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.TapestryDesigner_MetaBlocks", "ParentAppId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Nexus_TCP_Socket_Listener", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Master_UsersApplications", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Tapestry_WorkFlow", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Persona_ADgroup_User", "ADgroupId", "dbo.Persona_ADgroups", "Id");
            AddForeignKey("dbo.Persona_ADgroup_User", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_UserClaim", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_UserLogin", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_ModuleAccessPermissions", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_Identity_UserRoles", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_User_Role", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Master_UsersApplications", "UserId", "dbo.Persona_Users", "Id");
            AddForeignKey("dbo.Persona_User_Role", "ApplicationId", "dbo.Master_Applications", "Id");
            AddForeignKey("dbo.Entitron_DbRelation", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id");
            AddForeignKey("dbo.Entitron_DbTable", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id");
            AddForeignKey("dbo.Entitron_DbView", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id");
            AddForeignKey("dbo.Entitron_DbRelation", "LeftColumnId", "dbo.Entitron_DbColumn", "Id");
            AddForeignKey("dbo.Entitron_DbRelation", "LeftTableId", "dbo.Entitron_DbTable", "Id");
            AddForeignKey("dbo.Entitron_DbRelation", "RightColumnId", "dbo.Entitron_DbColumn", "Id");
            AddForeignKey("dbo.Entitron_DbRelation", "RightTableId", "dbo.Entitron_DbTable", "Id");
            AddForeignKey("dbo.Entitron_DbColumn", "DbTableId", "dbo.Entitron_DbTable", "Id");
            AddForeignKey("dbo.Entitron_DbIndex", "DbTableId", "dbo.Entitron_DbTable", "Id");
            AddForeignKey("dbo.Hermes_Incoming_Email_Rule", "IncomingEmailId", "dbo.Hermes_Incoming_Email", "Id");
            AddForeignKey("dbo.MozaicBootstrap_Components", "MozaicBootstrapPageId", "dbo.MozaicBootstrap_Page", "Id");
            AddForeignKey("dbo.MozaicEditor_Components", "MozaicEditorPageId", "dbo.MozaicEditor_Pages", "Id");
            AddForeignKey("dbo.TapestryDesigner_ResourceItems", "ParentRuleId", "dbo.TapestryDesigner_ResourceRules", "Id");
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "SourceId", "dbo.TapestryDesigner_ResourceItems", "Id");
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "TargetId", "dbo.TapestryDesigner_ResourceItems", "Id");
            AddForeignKey("dbo.TapestryDesigner_ConditionSets", "ConditionGroupId", "dbo.TapestryDesigner_ConditionGroups", "Id");
            AddForeignKey("dbo.TapestryDesigner_Conditions", "TapestryDesignerConditionSet_Id", "dbo.TapestryDesigner_ConditionSets", "Id");
            AddForeignKey("dbo.TapestryDesigner_WorkflowItems", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id");
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "SourceId", "dbo.TapestryDesigner_WorkflowItems", "Id");
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "TargetId", "dbo.TapestryDesigner_WorkflowItems", "Id");
            AddForeignKey("dbo.TapestryDesigner_Foreach", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id");
            AddForeignKey("dbo.TapestryDesigner_Swimlanes", "ParentWorkflowRule_Id", "dbo.TapestryDesigner_WorkflowRules", "Id");
            AddForeignKey("dbo.TapestryDesigner_Subflow", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id");
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "WorkflowRuleId", "dbo.TapestryDesigner_WorkflowRules", "Id");
            AddForeignKey("dbo.TapestryDesigner_WorkflowRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits", "Id");
            AddForeignKey("dbo.TapestryDesigner_BlocksCommits", "ParentBlock_Id", "dbo.TapestryDesigner_Blocks", "Id");
            AddForeignKey("dbo.TapestryDesigner_ResourceRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits", "Id");
            AddForeignKey("dbo.TapestryDesigner_Blocks", "ParentMetablock_Id", "dbo.TapestryDesigner_MetaBlocks", "Id");
            AddForeignKey("dbo.TapestryDesigner_MetablocksConnections", "TapestryDesignerMetablockId", "dbo.TapestryDesigner_MetaBlocks", "Id");
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "ResourceRuleId", "dbo.TapestryDesigner_ResourceRules", "Id");
            AddForeignKey("dbo.Tapestry_Blocks", "WorkFlowId", "dbo.Tapestry_WorkFlow", "Id");
            AddForeignKey("dbo.Tapestry_AttributeRules", "BlockId", "dbo.Tapestry_Blocks", "Id");
            AddForeignKey("dbo.Tapestry_PreBlockActions", "BlockId", "dbo.Tapestry_Blocks", "Id");
            AddForeignKey("dbo.Tapestry_ResourceMappingPairs", "BlockId", "dbo.Tapestry_Blocks", "Id");
            AddForeignKey("dbo.Mozaic_CssPages", "CssId", "dbo.Mozaic_Css", "Id");
            AddForeignKey("dbo.Mozaic_CssPages", "PageId", "dbo.Mozaic_Pages", "Id");
            AddForeignKey("dbo.Mozaic_Template", "CategoryId", "dbo.Mozaic_TemplateCategories", "Id");

            Sql("DROP TRIGGER [Trigger_ApplicationsToMetaBlockANDWorkFlow_CASCADE]");
            Sql("DROP TRIGGER [Trigger_PageComponent_CASCADE]");
            Sql("DROP TRIGGER [Trigger_BlockTargetTo]");
            Sql("DROP TRIGGER [Trigger_WorkFlow_Blocks_Cascade]");
            Sql("DROP TRIGGER [Trigger_BlockToBlocksCommit]");
            Sql("DROP TRIGGER [Trigger_BlockCommitToRules]");
            Sql("DROP TRIGGER [Trigger_MetaBlockToBlocks]");
            Sql("DROP TRIGGER [Trigger_ResourceConnectionSourceTarget]");
            Sql("DROP TRIGGER [Trigger_ResourceRulesToConnection]");
            Sql("DROP TRIGGER [Trigger_SwimlaneWFItems_CASCADE]");
            Sql("DROP TRIGGER [Trigger_WorkflowConnectionSourceTarget_CASCADE]");
            Sql("DROP TRIGGER [Trigger_WorkflowRulesToConnectionSwimlane_CASCADE]");

            Sql("CREATE TRIGGER [TRG_C:Entitron_DbColumn] ON [Entitron_DbColumn] INSTEAD OF DELETE AS BEGIN DELETE FROM [Entitron_DbRelation] WHERE [LeftColumnId] IN (SELECT [Id] FROM deleted) OR [RightColumnId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbColumn] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Entitron_DbSchemeCommit] ON [Entitron_DbSchemeCommit] INSTEAD OF DELETE AS BEGIN DELETE FROM [Entitron_DbRelation] WHERE [DbSchemeCommitId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbTable] WHERE [DbSchemeCommitId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbView] WHERE [DbSchemeCommitId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbSchemeCommit] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Entitron_DbTable] ON [Entitron_DbTable] INSTEAD OF DELETE AS BEGIN DELETE FROM [Entitron_DbRelation] WHERE [LeftTableId] IN (SELECT [Id] FROM deleted) OR [RightTableId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbColumn] WHERE [DbTableId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbIndex] WHERE [DbTableId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbTable] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Hermes_Email_Template] ON [Hermes_Email_Template] INSTEAD OF DELETE AS BEGIN DELETE FROM [Hermes_Email_Template_Content] WHERE [Hermes_Email_Template_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Email_Placeholder] WHERE [Hermes_Email_Template_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Email_Template] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Hermes_Incoming_Email] ON [Hermes_Incoming_Email] INSTEAD OF DELETE AS BEGIN DELETE FROM [Hermes_Incoming_Email_Rule] WHERE [IncomingEmailId] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Incoming_Email] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Master_Applications] ON [Master_Applications] INSTEAD OF DELETE AS BEGIN DELETE FROM [Entitron___META] WHERE [ApplicationName] IN (SELECT [Name] FROM deleted); DELETE FROM [Persona_AppRoles] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_User_Role] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_ColumnMetadata] WHERE [Application_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Entitron_DbSchemeCommit] WHERE [Application_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Email_Template] WHERE [AppId] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Incoming_Email_Rule] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Mozaic_Js] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicBootstrap_Page] WHERE [ParentApp_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicEditor_Pages] WHERE [ParentApp_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ConditionGroups] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_MetaBlocks] WHERE [ParentAppId] IN (SELECT [Id] FROM deleted); DELETE FROM [Master_UsersApplications] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_WorkFlow] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Hermes_Email_Queue] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); DELETE FROM [Cortex_Task] WHERE [AppId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_ADgroups] WHERE [ApplicationId] IN (SELECT [Id] FROM deleted); UPDATE [Persona_Users] SET [DesignAppId] = NULL WHERE [DesignAppId] IN (SELECT [Id] FROM deleted); DELETE FROM [Master_Applications] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Mozaic_Pages] ON [Mozaic_Pages] INSTEAD OF DELETE AS BEGIN UPDATE [Tapestry_Blocks] SET [MozaicPageId] = NULL WHERE [MozaicPageId] IN (SELECT [Id] FROM deleted); DELETE FROM [Mozaic_Pages] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:MozaicBootstrap_Components] ON [MozaicBootstrap_Components] INSTEAD OF DELETE AS BEGIN DELETE FROM [MozaicBootstrap_Components] WHERE [ParentComponentId] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicBootstrap_Components] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:MozaicBootstrap_Page] ON [MozaicBootstrap_Page] INSTEAD OF DELETE AS BEGIN DELETE FROM [MozaicBootstrap_Components] WHERE [MozaicBootstrapPageId] IN (SELECT [Id] FROM deleted); UPDATE [Mozaic_Js] SET [MozaicBootstrapPageId] = NULL WHERE [MozaicBootstrapPageId] IN (SELECT [Id] FROM deleted); UPDATE [TapestryDesigner_ResourceItems] SET [BootstrapPageId] = NULL WHERE [BootstrapPageId] IN (SELECT [Id] FROM deleted); UPDATE [Tapestry_Blocks] SET [BootstrapPageId] = NULL WHERE [BootstrapPageId] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicBootstrap_Page] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:MozaicEditor_Components] ON [MozaicEditor_Components] INSTEAD OF DELETE AS BEGIN DELETE FROM [MozaicEditor_Components] WHERE [ParentComponentId] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicEditor_Components] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:MozaicEditor_Pages] ON [MozaicEditor_Pages] INSTEAD OF DELETE AS BEGIN DELETE FROM [MozaicEditor_Components] WHERE [MozaicEditorPageId] IN (SELECT [Id] FROM deleted); UPDATE [TapestryDesigner_ResourceItems] SET [PageId] = NULL WHERE [PageId] IN (SELECT [Id] FROM deleted); UPDATE [Tapestry_Blocks] SET [EditorPageId] = NULL WHERE [EditorPageId] IN (SELECT [Id] FROM deleted); DELETE FROM [MozaicEditor_Pages] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Nexus_FileMetadataRecords] ON [Nexus_FileMetadataRecords] INSTEAD OF DELETE AS BEGIN DELETE FROM [Nexus_CachedFiles] WHERE [Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Nexus_FileMetadataRecords] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Nexus_WebDavServers] ON [Nexus_WebDavServers] INSTEAD OF DELETE AS BEGIN DELETE FROM [Nexus_FileMetadataRecords] WHERE [WebDavServer_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [Nexus_WebDavServers] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Persona_ADgroups] ON [Persona_ADgroups] INSTEAD OF DELETE AS BEGIN DELETE FROM [Persona_ADgroup_User] WHERE [ADgroupId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_ADgroups] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Persona_AppRoles] ON [Persona_AppRoles] INSTEAD OF DELETE AS BEGIN DELETE FROM [Persona_ActionRuleRights] WHERE [AppRoleId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_User_Role] WHERE [ApplicationId] IN (SELECT [ApplicationId] FROM deleted) AND [RoleName] IN (SELECT [Name] FROM deleted); DELETE FROM [Persona_AppRoles] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Persona_Users] ON [Persona_Users] INSTEAD OF DELETE AS BEGIN DELETE FROM [Persona_ADgroup_User] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_UserClaim] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_UserLogin] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_ModuleAccessPermissions] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_User_Role] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Master_UsersApplications] WHERE [UserId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_Users] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Tapestry_ActionRule] ON [Tapestry_ActionRule] INSTEAD OF DELETE AS BEGIN DELETE FROM [Tapestry_ActionRule_Action] WHERE [ActionRuleId] IN (SELECT [Id] FROM deleted); DELETE FROM [Persona_ActionRuleRights] WHERE [ActionRuleId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_ActionRule] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Tapestry_Actors] ON [Tapestry_Actors] INSTEAD OF DELETE AS BEGIN DELETE FROM [Tapestry_ActionRule] WHERE [ActorId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_Actors] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Tapestry_Blocks] ON [Tapestry_Blocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [Tapestry_ActionRule] WHERE [SourceBlockId] IN (SELECT [Id] FROM deleted) OR [TargetBlockId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_ResourceMappingPairs] WHERE [BlockId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_Blocks] WHERE [IsVirtualForBlockId] IN (SELECT [Id] FROM deleted); UPDATE [Tapestry_WorkFlow] SET [InitBlockId] = NULL WHERE [InitBlockId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_Blocks] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Tapestry_WorkFlow] ON [Tapestry_WorkFlow] INSTEAD OF DELETE AS BEGIN DELETE FROM [Tapestry_Blocks] WHERE [WorkFlowId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_WorkFlow] WHERE [ParentId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_WorkFlow] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:Tapestry_WorkFlow_Types] ON [Tapestry_WorkFlow_Types] INSTEAD OF DELETE AS BEGIN DELETE FROM [Tapestry_WorkFlow] WHERE [TypeId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_WorkFlow_Types] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_Blocks] ON [TapestryDesigner_Blocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_MetablocksConnections] WHERE ([SourceType] = 0 AND [SourceId] IN (SELECT [Id] FROM deleted)) OR ([TargetType] = 0 AND [TargetId] IN (SELECT [Id] FROM deleted)); DELETE FROM [TapestryDesigner_BlocksCommits] WHERE [ParentBlock_Id] IN (SELECT [Id] FROM deleted); UPDATE [TapestryDesigner_WorkflowItems] SET [TargetId] = NULL WHERE [TargetId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Blocks] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_BlocksCommits] ON [TapestryDesigner_BlocksCommits] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_ToolboxStates] WHERE [AssociatedBlockCommit_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_WorkflowRules] WHERE [ParentBlockCommit_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ResourceRules] WHERE [ParentBlockCommit_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_BlocksCommits] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_ConditionGroups] ON [TapestryDesigner_ConditionGroups] INSTEAD OF DELETE AS BEGIN UPDATE [Tapestry_ActionRule] SET [ConditionGroupId] = NULL WHERE [ConditionGroupId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ConditionSets] WHERE [ConditionGroupId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ConditionGroups] WHERE Id IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_ConditionSets] ON [TapestryDesigner_ConditionSets] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_Conditions] WHERE [TapestryDesignerConditionSet_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ConditionSets] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_Foreach] ON [TapestryDesigner_Foreach] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_WorkflowItems] WHERE [ParentForeachId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Foreach] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_MetaBlocks] ON [TapestryDesigner_MetaBlocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_MetablocksConnections] WHERE [TapestryDesignerMetablockId] IN (SELECT [Id] FROM deleted) OR ([SourceType] = 1 AND [SourceId] IN (SELECT [Id] FROM deleted)) OR ([TargetType] = 1 AND [TargetId] IN (SELECT [Id] FROM deleted)); DELETE FROM [TapestryDesigner_Blocks] WHERE [ParentMetaBlock_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_MetaBlocks] WHERE [ParentMetaBlock_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_MetaBlocks] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_ResourceItems] ON [TapestryDesigner_ResourceItems] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_ResourceConnections] WHERE [SourceId] IN (SELECT [Id] FROM deleted) OR [TargetId] IN (SELECT [Id] FROM deleted); DELETE FROM [Tapestry_ResourceMappingPairs] WHERE [Source_Id] IN (SELECT [Id] FROM deleted) OR [Target_Id] IN (SELECT [Id] FROM deleted); UPDATE [TapestryDesigner_ConditionGroups] SET [TapestryDesignerResourceItemId] = NULL WHERE [TapestryDesignerResourceItemId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ResourceItems] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_ResourceRules] ON [TapestryDesigner_ResourceRules] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_ResourceItems] WHERE [ParentRuleId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ResourceConnections] WHERE [ResourceRuleId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ResourceRules] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_Subflow] ON [TapestryDesigner_Subflow] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_WorkflowItems] WHERE [ParentSubflowId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Subflow] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_Swimlanes] ON [TapestryDesigner_Swimlanes] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_WorkflowItems] WHERE [ParentSwimlaneId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Foreach] WHERE [ParentSwimlaneId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Subflow] WHERE [ParentSwimlaneId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Swimlanes] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_ToolboxStates] ON [TapestryDesigner_ToolboxStates] INSTEAD OF DELETE AS BEGIN UPDATE [TapestryDesigner_Blocks] SET [ToolboxState_Id] = NULL WHERE [ToolboxState_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id1] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id2] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id3] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id4] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id5] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id6] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxItems] WHERE [TapestryDesignerToolboxState_Id7] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_ToolboxStates] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_WorkflowItems] ON [TapestryDesigner_WorkflowItems] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_WorkflowConnections] WHERE [SourceId] IN (SELECT [Id] FROM deleted) OR [TargetId] IN (SELECT [Id] FROM deleted); UPDATE [TapestryDesigner_ConditionGroups] SET [TapestryDesignerWorkflowItemId] = NULL WHERE [TapestryDesignerWorkflowItemId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_WorkflowItems] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
            Sql("CREATE TRIGGER [TRG_C:TapestryDesigner_WorkflowRules] ON [TapestryDesigner_WorkflowRules] INSTEAD OF DELETE AS BEGIN DELETE FROM [TapestryDesigner_WorkflowConnections] WHERE [WorkflowRuleId] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_Swimlanes] WHERE [ParentWorkflowRule_Id] IN (SELECT [Id] FROM deleted); DELETE FROM [TapestryDesigner_WorkflowRules] WHERE [Id] IN (SELECT [Id] FROM deleted); END");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Mozaic_Template", "CategoryId", "dbo.Mozaic_TemplateCategories");
            DropForeignKey("dbo.Mozaic_CssPages", "PageId", "dbo.Mozaic_Pages");
            DropForeignKey("dbo.Mozaic_CssPages", "CssId", "dbo.Mozaic_Css");
            DropForeignKey("dbo.Tapestry_ResourceMappingPairs", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Tapestry_PreBlockActions", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Tapestry_AttributeRules", "BlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Tapestry_Blocks", "WorkFlowId", "dbo.Tapestry_WorkFlow");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "ResourceRuleId", "dbo.TapestryDesigner_ResourceRules");
            DropForeignKey("dbo.TapestryDesigner_MetablocksConnections", "TapestryDesignerMetablockId", "dbo.TapestryDesigner_MetaBlocks");
            DropForeignKey("dbo.TapestryDesigner_Blocks", "ParentMetablock_Id", "dbo.TapestryDesigner_MetaBlocks");
            DropForeignKey("dbo.TapestryDesigner_ResourceRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits");
            DropForeignKey("dbo.TapestryDesigner_BlocksCommits", "ParentBlock_Id", "dbo.TapestryDesigner_Blocks");
            DropForeignKey("dbo.TapestryDesigner_WorkflowRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "WorkflowRuleId", "dbo.TapestryDesigner_WorkflowRules");
            DropForeignKey("dbo.TapestryDesigner_Subflow", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_Swimlanes", "ParentWorkflowRule_Id", "dbo.TapestryDesigner_WorkflowRules");
            DropForeignKey("dbo.TapestryDesigner_Foreach", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "TargetId", "dbo.TapestryDesigner_WorkflowItems");
            DropForeignKey("dbo.TapestryDesigner_WorkflowConnections", "SourceId", "dbo.TapestryDesigner_WorkflowItems");
            DropForeignKey("dbo.TapestryDesigner_WorkflowItems", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes");
            DropForeignKey("dbo.TapestryDesigner_Conditions", "TapestryDesignerConditionSet_Id", "dbo.TapestryDesigner_ConditionSets");
            DropForeignKey("dbo.TapestryDesigner_ConditionSets", "ConditionGroupId", "dbo.TapestryDesigner_ConditionGroups");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "TargetId", "dbo.TapestryDesigner_ResourceItems");
            DropForeignKey("dbo.TapestryDesigner_ResourceConnections", "SourceId", "dbo.TapestryDesigner_ResourceItems");
            DropForeignKey("dbo.TapestryDesigner_ResourceItems", "ParentRuleId", "dbo.TapestryDesigner_ResourceRules");
            DropForeignKey("dbo.MozaicEditor_Components", "MozaicEditorPageId", "dbo.MozaicEditor_Pages");
            DropForeignKey("dbo.MozaicBootstrap_Components", "MozaicBootstrapPageId", "dbo.MozaicBootstrap_Page");
            DropForeignKey("dbo.Hermes_Incoming_Email_Rule", "IncomingEmailId", "dbo.Hermes_Incoming_Email");
            DropForeignKey("dbo.Entitron_DbIndex", "DbTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbColumn", "DbTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbRelation", "RightTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbRelation", "RightColumnId", "dbo.Entitron_DbColumn");
            DropForeignKey("dbo.Entitron_DbRelation", "LeftTableId", "dbo.Entitron_DbTable");
            DropForeignKey("dbo.Entitron_DbRelation", "LeftColumnId", "dbo.Entitron_DbColumn");
            DropForeignKey("dbo.Entitron_DbView", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Entitron_DbTable", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Entitron_DbRelation", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit");
            DropForeignKey("dbo.Persona_User_Role", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Master_UsersApplications", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_User_Role", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_Identity_UserRoles", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_ModuleAccessPermissions", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_UserLogin", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_UserClaim", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_ADgroup_User", "UserId", "dbo.Persona_Users");
            DropForeignKey("dbo.Persona_ADgroup_User", "ADgroupId", "dbo.Persona_ADgroups");
            DropForeignKey("dbo.Tapestry_WorkFlow", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Master_UsersApplications", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Nexus_TCP_Socket_Listener", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.TapestryDesigner_MetaBlocks", "ParentAppId", "dbo.Master_Applications");
            DropForeignKey("dbo.MozaicEditor_Pages", "ParentApp_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.MozaicBootstrap_Page", "ParentApp_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.Mozaic_Js", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Hermes_Incoming_Email_Rule", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Entitron_DbSchemeCommit", "Application_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.Entitron_ColumnMetadata", "Application_Id", "dbo.Master_Applications");
            DropForeignKey("dbo.Persona_AppRoles", "ApplicationId", "dbo.Master_Applications");
            DropForeignKey("dbo.Persona_ActionRuleRights", "AppRoleId", "dbo.Persona_AppRoles");
            DropForeignKey("dbo.Tapestry_ActionRule", "SourceBlockId", "dbo.Tapestry_Blocks");
            DropForeignKey("dbo.Persona_ActionRuleRights", "ActionRuleId", "dbo.Tapestry_ActionRule");
            DropForeignKey("dbo.Tapestry_ActionRule_Action", "ActionRuleId", "dbo.Tapestry_ActionRule");
            AddForeignKey("dbo.Mozaic_Template", "CategoryId", "dbo.Mozaic_TemplateCategories", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Mozaic_CssPages", "PageId", "dbo.Mozaic_Pages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Mozaic_CssPages", "CssId", "dbo.Mozaic_Css", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_ResourceMappingPairs", "BlockId", "dbo.Tapestry_Blocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_PreBlockActions", "BlockId", "dbo.Tapestry_Blocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_AttributeRules", "BlockId", "dbo.Tapestry_Blocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_Blocks", "WorkFlowId", "dbo.Tapestry_WorkFlow", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "ResourceRuleId", "dbo.TapestryDesigner_ResourceRules", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_MetablocksConnections", "TapestryDesignerMetablockId", "dbo.TapestryDesigner_MetaBlocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_Blocks", "ParentMetablock_Id", "dbo.TapestryDesigner_MetaBlocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ResourceRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_BlocksCommits", "ParentBlock_Id", "dbo.TapestryDesigner_Blocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_WorkflowRules", "ParentBlockCommit_Id", "dbo.TapestryDesigner_BlocksCommits", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "WorkflowRuleId", "dbo.TapestryDesigner_WorkflowRules", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_Subflow", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_Swimlanes", "ParentWorkflowRule_Id", "dbo.TapestryDesigner_WorkflowRules", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_Foreach", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "TargetId", "dbo.TapestryDesigner_WorkflowItems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_WorkflowConnections", "SourceId", "dbo.TapestryDesigner_WorkflowItems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_WorkflowItems", "ParentSwimlaneId", "dbo.TapestryDesigner_Swimlanes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_Conditions", "TapestryDesignerConditionSet_Id", "dbo.TapestryDesigner_ConditionSets", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ConditionSets", "ConditionGroupId", "dbo.TapestryDesigner_ConditionGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "TargetId", "dbo.TapestryDesigner_ResourceItems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ResourceConnections", "SourceId", "dbo.TapestryDesigner_ResourceItems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_ResourceItems", "ParentRuleId", "dbo.TapestryDesigner_ResourceRules", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MozaicEditor_Components", "MozaicEditorPageId", "dbo.MozaicEditor_Pages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MozaicBootstrap_Components", "MozaicBootstrapPageId", "dbo.MozaicBootstrap_Page", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Hermes_Incoming_Email_Rule", "IncomingEmailId", "dbo.Hermes_Incoming_Email", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbIndex", "DbTableId", "dbo.Entitron_DbTable", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbColumn", "DbTableId", "dbo.Entitron_DbTable", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbRelation", "RightTableId", "dbo.Entitron_DbTable", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbRelation", "RightColumnId", "dbo.Entitron_DbColumn", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbRelation", "LeftTableId", "dbo.Entitron_DbTable", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbRelation", "LeftColumnId", "dbo.Entitron_DbColumn", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbView", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbTable", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbRelation", "DbSchemeCommitId", "dbo.Entitron_DbSchemeCommit", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_User_Role", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Master_UsersApplications", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_User_Role", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_Identity_UserRoles", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_ModuleAccessPermissions", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_UserLogin", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_UserClaim", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_ADgroup_User", "UserId", "dbo.Persona_Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_ADgroup_User", "ADgroupId", "dbo.Persona_ADgroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_WorkFlow", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Master_UsersApplications", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Nexus_TCP_Socket_Listener", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TapestryDesigner_MetaBlocks", "ParentAppId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MozaicEditor_Pages", "ParentApp_Id", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MozaicBootstrap_Page", "ParentApp_Id", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Mozaic_Js", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Hermes_Incoming_Email_Rule", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_DbSchemeCommit", "Application_Id", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Entitron_ColumnMetadata", "Application_Id", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_AppRoles", "ApplicationId", "dbo.Master_Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_ActionRuleRights", "AppRoleId", "dbo.Persona_AppRoles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_ActionRule", "SourceBlockId", "dbo.Tapestry_Blocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Persona_ActionRuleRights", "ActionRuleId", "dbo.Tapestry_ActionRule", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tapestry_ActionRule_Action", "ActionRuleId", "dbo.Tapestry_ActionRule", "Id", cascadeDelete: true);

            Sql("DROP TRIGGER [TRG_C:Entitron_DbColumn];");
            Sql("DROP TRIGGER [TRG_C:Entitron_DbSchemeCommit];");
            Sql("DROP TRIGGER [TRG_C:Entitron_DbTable];");
            Sql("DROP TRIGGER [TRG_C:Hermes_Email_Template];");
            Sql("DROP TRIGGER [TRG_C:Hermes_Incoming_Email];");
            Sql("DROP TRIGGER [TRG_C:Master_Applications];");
            Sql("DROP TRIGGER [TRG_C:Mozaic_Pages];");
            Sql("DROP TRIGGER [TRG_C:MozaicBootstrap_Components];");
            Sql("DROP TRIGGER [TRG_C:MozaicBootstrap_Page];");
            Sql("DROP TRIGGER [TRG_C:MozaicEditor_Components];");
            Sql("DROP TRIGGER [TRG_C:MozaicEditor_Pages];");
            Sql("DROP TRIGGER [TRG_C:Nexus_FileMetadataRecords];");
            Sql("DROP TRIGGER [TRG_C:Nexus_WebDavServers];");
            Sql("DROP TRIGGER [TRG_C:Persona_ADgroups];");
            Sql("DROP TRIGGER [TRG_C:Persona_AppRoles];");
            Sql("DROP TRIGGER [TRG_C:Persona_Users];");
            Sql("DROP TRIGGER [TRG_C:Tapestry_ActionRule];");
            Sql("DROP TRIGGER [TRG_C:Tapestry_Actors];");
            Sql("DROP TRIGGER [TRG_C:Tapestry_Blocks];");
            Sql("DROP TRIGGER [TRG_C:Tapestry_WorkFlow];");
            Sql("DROP TRIGGER [TRG_C:Tapestry_WorkFlow_Types];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_Blocks];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_BlocksCommits];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_ConditionSets];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_Foreach];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_MetaBlocks];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_ResourceItems];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_ResourceRules];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_Subflow];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_Swimlanes];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_ToolboxStates];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_WorkflowItems];");
            Sql("DROP TRIGGER [TRG_C:TapestryDesigner_WorkflowRules];");

            Sql("CREATE TRIGGER [dbo].[Trigger_SwimlaneWFItems_CASCADE] ON [dbo].[TapestryDesigner_Swimlanes] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_WorkflowItems] WHERE [ParentSwimlaneId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_Swimlanes] WHERE [Id] IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_WorkflowConnectionSourceTarget_CASCADE] ON [dbo].[TapestryDesigner_WorkflowItems] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_WorkflowConnections] WHERE [SourceId] IN (SELECT Id FROM deleted) OR [TargetId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_WorkflowItems] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_WorkflowRulesToConnectionSwimlane_CASCADE] ON [dbo].[TapestryDesigner_WorkflowRules] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_WorkflowConnections] WHERE [WorkflowRuleId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_Swimlanes] WHERE [ParentWorkflowRule_Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_WorkflowRules] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_ApplicationsToMetaBlockANDWorkFlow_CASCADE] ON [dbo].[Master_Applications] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[Tapestry_WorkFlow] WHERE [ApplicationId] IN (SELECT Id FROM deleted);UPDATE [dbo].[TapestryDesigner_MetaBlocks] SET [ParentMetablock_Id] = NULL WHERE [ParentAppId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[TapestryDesigner_MetaBlocks] WHERE [ParentAppId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[Entitron_DbSchemeCommit] WHERE [ApplicationId] IN (SELECT Id FROM deleted);UPDATE [dbo].[Persona_ADgroups] SET [ApplicationId] = NULL WHERE [ApplicationId] IN (SELECT Id FROM deleted);UPDATE [dbo].[Entitron___META] SET [ApplicationId] = NULL WHERE [ApplicationId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[MozaicEditor_Pages] WHERE [ParentApp_Id] IN (SELECT Id FROM deleted);UPDATE [dbo].[Persona_Users] SET [DesignAppId] = NULL WHERE [DesignAppId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[Master_Applications] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_PageComponent_CASCADE] ON [dbo].[MozaicEditor_Pages] INSTEAD OF DELETE AS BEGIN UPDATE [dbo].[MozaicEditor_Components] SET [ParentComponentId] = NULL WHERE [MozaicEditorPageId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[MozaicEditor_Components] WHERE [MozaicEditorPageId] IN (SELECT Id FROM deleted);DELETE FROM [dbo].[MozaicEditor_Pages] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_WorkFlow_Blocks_Cascade] ON [dbo].[Tapestry_WorkFlow] INSTEAD OF DELETE AS BEGIN UPDATE [dbo].[Tapestry_WorkFlow] SET [InitBlockId] = NULL, [ParentId] = NULL WHERE [Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[Tapestry_Blocks] WHERE [WorkFlowId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[Tapestry_WorkFlow] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_BlockTargetTo] ON [dbo].[Tapestry_Blocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[Tapestry_ActionRule] WHERE [TargetBlockId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[Tapestry_Blocks] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_MetaBlockToBlocks] ON [dbo].[TapestryDesigner_MetaBlocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_Blocks] WHERE [ParentMetablock_Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_MetaBlocks] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_BlockToBlocksCommit] ON [dbo].[TapestryDesigner_Blocks] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_BlocksCommits] WHERE [ParentBlock_Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_Blocks] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_BlockCommitToRules] ON [dbo].[TapestryDesigner_BlocksCommits] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_ResourceRules] WHERE [ParentBlockCommit_Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_WorkflowRules] WHERE [ParentBlockCommit_Id] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_BlocksCommits] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_ResourceConnectionSourceTarget] ON [dbo].[TapestryDesigner_ResourceItems] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_ResourceConnections] WHERE [SourceId] IN (SELECT Id FROM deleted) OR [TargetId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_ResourceItems] WHERE Id IN (SELECT Id FROM deleted); END");
            Sql("CREATE TRIGGER [dbo].[Trigger_ResourceRulesToConnection] ON [dbo].[TapestryDesigner_ResourceRules] INSTEAD OF DELETE AS BEGIN DELETE FROM [dbo].[TapestryDesigner_ResourceConnections] WHERE [ResourceRuleId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_ResourceItems] WHERE [ParentRuleId] IN (SELECT Id FROM deleted); DELETE FROM [dbo].[TapestryDesigner_ResourceRules] WHERE Id IN (SELECT Id FROM deleted); END");
        }
    }
}
