// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mozaiceditorparentcomponent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mozaiceditorparentcomponent));
        
        string IMigrationMetadata.Id
        {
            get { return "201603281221022_Mozaic editor parent component"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
