// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addconditionsetstogateways : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addconditionsetstogateways));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041236075_Add condition sets to gateways"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
