// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mozaicmodalsettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mozaicmodalsettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201602251931211_Mozaic - modal settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
