// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddmigrationforassigningapplicationrolesbyADgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddmigrationforassigningapplicationrolesbyADgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201707030945512_Add migration for assigning application roles by AD group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
