// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntitronMeta_applicationName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntitronMeta_applicationName));
        
        string IMigrationMetadata.Id
        {
            get { return "201704211146487_EntitronMeta_applicationName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
