// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class schemeLockerforuserid_added_to_application : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schemeLockerforuserid_added_to_application));
        
        string IMigrationMetadata.Id
        {
            get { return "201702281055524_schemeLockerforuserid_added_to_application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
