// <auto-generated />
namespace FSS.Omnius.Modules.Migrations.MSSQL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonaMultiAuth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonaMultiAuth));
        
        string IMigrationMetadata.Id
        {
            get { return "201808300730052_PersonaMultiAuth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
